# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:

include:
# - board: nice_nano_v2
#   shield: kirinv2
#   snippet: studio-rpc-usb-uart zmk-usb-logging
# - board: nice_nano_v2
#   shield: settings_reset
#   snippet: studio-rpc-usb-uart
- board: supermini_rp2040
  shield: kirinv2
  snippet: studio-rpc-usb-uart zmk-usb-logging
- board: supermini_rp2040
  shield: settings_reset
  snippet: studio-rpc-usb-uart